package simu.framework;

import eduni.distributions.ContinuousGenerator;
import simu.model.EventType;

/**
 * The ArrivalProcess class represents the arrival process of customers in a simulation framework.
 * It generates arrival events based on a continuous generator and adds them to the event list.
 */
public class ArrivalProcess {
	private ContinuousGenerator generator;
	private EventList eventList;
	private EventType eventType;
	private int customerCount = 0;
	private final int maxCustomers;

	/**
	 * Constructs an ArrivalProcess object with the specified parameters.
	 *
	 * @param generator    The continuous generator for generating arrival times.
	 * @param eventList    The event list to which the generated arrival events will be added.
	 * @param eventType    The type of event representing arrivals.
	 * @param maxCustomers The maximum number of customers to be generated by the arrival process.
	 */
	public ArrivalProcess(ContinuousGenerator generator, EventList eventList, EventType eventType, int maxCustomers) {
		this.generator = generator;
		this.eventList = eventList;
		this.eventType = eventType;
		this.maxCustomers = maxCustomers;
	}

	/**
	 * Generates the next arrival event if the maximum number of customers has not been reached yet.
	 * If the maximum number of customers has been reached, no new arrival event is generated.
	 */
	public void generateNext() {
		if (customerCount < maxCustomers) {
			eventList.add(new Event(eventType, generator.sample()));
			customerCount++;
		}
	}
}
